fastlane_version "2.103.0"

default_platform :ios

platform :ios do
  before_all do
    # clean_build_artifacts
    # clear_derived_data
    # ensure_git_status_clean
    # cocoapods
    # increment_build_number
    # xctool
  end

  desc "Runs all the tests"
  lane :test do
    snapshot
    frameit
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    sigh
    gym(scheme: "BiciMAD")
    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :deploy do
    snapshot
    sigh
    gym(scheme: "BiciMAD")
    deliver(force: true)
    frameit
  end
 
  after_all do |lane|
  end

  error do |lane, exception|
  end
end