devices([
  "iPhone 6",
  "iPhone 6 Plus",
  "iPhone 5",
  "iPhone 4s",
  "iPad Retina",
  "iPad Pro"
])

languages([
  "en-US",
  "es-ES"
])

scheme "BiciMAD"

# output_directory "./screenshots"

clear_previous_screenshots

# project "./Project.xcodeproj"
# workspace "./Project.xcworkspace"